# Basic
language: objective-c
osx_image: xcode8

script: xcodebuild -workspace AFNetworking+RetryPolicy Example/AFNetworking+RetryPolicy Example.xcworkspace -scheme AFNetworking+RetryPolicy Example -sdk iphonesimulator -destination "OS=10.0,name=iPhone SE"


# CocoaPods
podfile: AFNetworking+RetryPolicy Example/Podfile

# Notifications
notifications:
  email: false
