# Basic
language: objective-c
osx_image: xcode8
xcode_scheme: AFNetworking+RetryPolicy Example
xcode_workspace: AFNetworking+RetryPolicy Example/AFNetworking+RetryPolicy Example.xcworkspace

# Test on simulator (Does not require code signing)
xcode_sdk: iphonesimulator10.0

# CocoaPods
podfile: AFNetworking+RetryPolicy Example/Podfile

# Notifications
notifications:
  email: false
