# Basic
language: objective-c
osx_image: xcode8
xcode_scheme: AFNetworking+RetryPolicy Example
xcode_workspace: AFNetworking+RetryPolicy Example/AFNetworking+RetryPolicy Example.xcworkspace

# CocoaPods
podfile: AFNetworking+RetryPolicy Example/Podfile

# Notifications
notifications:
  email: false
