# DO WORK WITH XCODE 8 SINCE xcodebuild IS SUPPORTING IT.
#
# Basic
language: objective-c
osx_image: xcode8
script: xcodebuild -workspace Example/Example.xcworkspace -scheme Example -sdk iphonesimulator10.0

# CocoaPods
podfile: AFNetworking+RetryPolicy Example/Podfile

# Notifications
notifications:
  email: false

# ------------------------------------------------------------
# DO NOT WORK WITH XCODE 8 SINCE xctools IS NOT SUPPORTING IT.
#
## Basic
#language: objective-c
#osx_image: xcode7.3
#xcode_scheme: AFNetworking+RetryPolicy Example
#xcode_workspace: AFNetworking+RetryPolicy Example/AFNetworking+RetryPolicy Example.xcworkspace
#
## Test on simulator (Does not require code signing)
#xcode_sdk: iphonesimulator9.3
#
## CocoaPods
#podfile: AFNetworking+RetryPolicy Example/Podfile
#
## Notifications
#notifications:
#email: false
